# Retro theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#f2f1e4"
base01 = "#e9e6d6"
base02 = "#d0c9c5"
base03 = "#a39e9b"
base04 = "#868282"
base05 = "#6e6a73"
base06 = "#544d56"
base07 = "#2c2837"
base08 = "#b75a5a"
base09 = "#b7803f"
base0A = "#a8a04a"
base0B = "#709a68"
base0C = "#5f969a"
base0D = "#5d7595"
base0E = "#8470a0"
base0F = "#8a6f5a"
