# Aikido theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#262626"
base01 = "#333333"
base02 = "#3b3028"
base03 = "#54433a"
base04 = "#6c5d53"
base05 = "#a29990"
base06 = "#cbc3bc"
base07 = "#f6f5f0"
base08 = "#4d5645"
base09 = "#835538"
base0A = "#bfa46f"
base0B = "#d7503c"
base0C = "#8694a8"
base0D = "#658fbd"
base0E = "#896ea4"
base0F = "#7a5c42"
