# Green theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#c9e8ce"
base01 = "#b9d7be"
base02 = "#a8cea9"
base03 = "#91b992"
base04 = "#67996f"
base05 = "#4b835a"
base06 = "#2d5c35"
base07 = "#193821"
base08 = "#d44246"
base09 = "#e07336"
base0A = "#e2b53a"
base0B = "#5db32b"
base0C = "#3bb5c3"
base0D = "#4284d3"
base0E = "#a94dd0"
base0F = "#8f6a42"
