# Forest Night theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#0f1a12"
base01 = "#192821"
base02 = "#2c3c2f"
base03 = "#435645"
base04 = "#678568"
base05 = "#8aa894"
base06 = "#b3c4ba"
base07 = "#ebefe9"
base08 = "#abcb7e"
base09 = "#e3c078"
base0A = "#c9b154"
base0B = "#78a8c0"
base0C = "#a5d6e7"
base0D = "#604c38"
base0E = "#85a7b3"
base0F = "#8f7a5e"
