# Futuristic theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#f7f8fc"
base01 = "#e4e6f1"
base02 = "#c9ccd8"
base03 = "#8f93a2"
base04 = "#676e95"
base05 = "#434759"
base06 = "#292d3e"
base07 = "#0f111a"
base08 = "#f0274a"
base09 = "#e8733a"
base0A = "#e6b455"
base0B = "#66bb6a"
base0C = "#42a5f5"
base0D = "#5c7ae9"
base0E = "#a258d0"
base0F = "#8b5a47"
