# Futuristic theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#0f111a"
base01 = "#1a1c25"
base02 = "#292d3e"
base03 = "#434759"
base04 = "#676e95"
base05 = "#8f93a2"
base06 = "#c9ccd8"
base07 = "#f7f8fc"
base08 = "#ff5370"
base09 = "#f78c6c"
base0A = "#ffcb6b"
base0B = "#c3e88d"
base0C = "#89ddff"
base0D = "#82aaff"
base0E = "#c792ea"
base0F = "#ab7967"
