# Desert theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#f7f3eb"
base01 = "#e8e1d4"
base02 = "#d0c8b9"
base03 = "#a08f80"
base04 = "#7e6b5d"
base05 = "#5d4a3e"
base06 = "#4d3c30"
base07 = "#2e231b"
base08 = "#4f5d49"
base09 = "#8d462b"
base0A = "#a17a46"
base0B = "#9c4427"
base0C = "#7c725e"
base0D = "#b15a19"
base0E = "#865532"
base0F = "#4a9f4a"
