# Desert theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#2e231b"
base01 = "#3d3026"
base02 = "#4d3c30"
base03 = "#5d4a3e"
base04 = "#7e6b5d"
base05 = "#a08f80"
base06 = "#d0c8b9"
base07 = "#f7f3eb"
base08 = "#6a7b62"
base09 = "#ab6444"
base0A = "#caa06c"
base0B = "#b35d3a"
base0C = "#968a75"
base0D = "#d2691e"
base0E = "#a37a58"
base0F = "#7ab87a"
