# Volcanic theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#e5e0dd"
base01 = "#ccc6c2"
base02 = "#a19a95"
base03 = "#746b66"
base04 = "#514845"
base05 = "#3f3734"
base06 = "#2c2624"
base07 = "#191514"
base08 = "#a8301f"
base09 = "#b45a1c"
base0A = "#a47b16"
base0B = "#3c7232"
base0C = "#3b6a67"
base0D = "#3c5985"
base0E = "#614f85"
base0F = "#7a5230"
