# Volcanic theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#191514"
base01 = "#2c2624"
base02 = "#3f3734"
base03 = "#514845"
base04 = "#746b66"
base05 = "#a19a95"
base06 = "#ccc6c2"
base07 = "#e5e0dd"
base08 = "#cc3f26"
base09 = "#de7c31"
base0A = "#e8b026"
base0B = "#5d9f4f"
base0C = "#5f9893"
base0D = "#5878aa"
base0E = "#9071b0"
base0F = "#a16946"
