# Blue theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#c4dcf2"
base01 = "#a7cbed"
base02 = "#8bb8e2"
base03 = "#7ba9d0"
base04 = "#5382a8"
base05 = "#335a7c"
base06 = "#1e3a64"
base07 = "#0a1e36"
base08 = "#d12f2f"
base09 = "#cb7832"
base0A = "#925a10"
base0B = "#2a8c2a"
base0C = "#2a8c8c"
base0D = "#2970b6"
base0E = "#7436b6"
base0F = "#4a9f4a"
