# Blue theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#0a1e36"
base01 = "#112a46"
base02 = "#1e3a64"
base03 = "#335a7c"
base04 = "#5382a8"
base05 = "#7ba9d0"
base06 = "#a8cde9"
base07 = "#deeef8"
base08 = "#e55a5a"
base09 = "#e5995a"
base0A = "#e5d15a"
base0B = "#5ae55a"
base0C = "#5ae5e5"
base0D = "#5a9de5"
base0E = "#a85ae5"
base0F = "#7ab87a"
