# Mainframe theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#331a00"
base01 = "#402000"
base02 = "#663300"
base03 = "#995000"
base04 = "#cc7a00"
base05 = "#e69500"
base06 = "#ffb000"
base07 = "#ffc266"
base08 = "#ff5555"
base09 = "#ffaa00"
base0A = "#ffcc44"
base0B = "#ffa04d"
base0C = "#ff9933"
base0D = "#ff8000"
base0E = "#e67300"
base0F = "#995000"
