# Nordic theme - day variant
# Scheme: vogix16

polarity = "light"

[colors]
base00 = "#eceff4"
base01 = "#e5e9f0"
base02 = "#d8dee9"
base03 = "#9099a9"
base04 = "#667385"
base05 = "#4c566a"
base06 = "#3b4252"
base07 = "#2e3440"
base08 = "#9d4149"
base09 = "#b46946"
base0A = "#c28252"
base0B = "#5e81ac"
base0C = "#70a7a6"
base0D = "#c78452"
base0E = "#a16896"
base0F = "#8b5f4a"
