# Nordic theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#2e3440"
base01 = "#3b4252"
base02 = "#434c5e"
base03 = "#4c566a"
base04 = "#667385"
base05 = "#9099a9"
base06 = "#d8dee9"
base07 = "#eceff4"
base08 = "#b04c58"
base09 = "#c67f53"
base0A = "#d09464"
base0B = "#81a1c1"
base0C = "#8fbcbb"
base0D = "#d8a174"
base0E = "#b48ead"
base0F = "#a3745f"
