# Orange theme - night variant
# Scheme: vogix16

polarity = "dark"

[colors]
base00 = "#2a1506"
base01 = "#40220c"
base02 = "#5c3213"
base03 = "#804515"
base04 = "#a65f1a"
base05 = "#d9915b"
base06 = "#e9b38c"
base07 = "#fff2e6"
base08 = "#e55545"
base09 = "#e5954f"
base0A = "#eace60"
base0B = "#75c458"
base0C = "#64b9c4"
base0D = "#569cd6"
base0E = "#b58cd9"
base0F = "#a16946"
